# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [108]:
nul = np.zeros(10)
nul

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [109]:
ran = np.arange(10,50)
ran

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [110]:
ran.shape

(40,)

5. Print the type of the previous array in question 3

In [111]:
ran.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [112]:
print(np.__version__, np.show_config())

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['e:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'e:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['e:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'e:/Anaconda3\\Library\\include']
blas_op

7. Print the dimension of the array in question 3


In [113]:
ran.ndim

1

8. Create a boolean array with all the True values

In [114]:
bb = np.array(range(1,5),dtype="bool" )
bb

array([ True,  True,  True,  True])

9. Create a two dimensional array




In [118]:
dd = np.random.randint(0,4,size=(2,2))
dd

array([[3, 1],
       [1, 2]])

10. Create a three dimensional array



In [119]:
ara = np.random.randn(4,4,2)
ara

array([[[-0.53101115, -1.1922537 ],
        [ 1.28283504, -2.21141714],
        [ 0.33107662,  0.15923732],
        [-1.46421788, -1.32106717]],

       [[ 1.21109651, -0.47615665],
        [-1.28149439, -0.75195426],
        [ 0.72324606,  1.35179089],
        [ 0.83156092, -0.15488737]],

       [[ 0.54162215,  1.76674707],
        [-0.38096306,  1.03240326],
        [ 1.36271716,  0.18648553],
        [-1.02962634,  1.57634834]],

       [[-0.5070661 ,  0.53183107],
        [-0.48872723, -1.20229901],
        [ 1.06795163,  0.51678264],
        [-0.74685146, -0.42279898]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [122]:
print ( "fwd = " ,dd)
print ( " rev = ", dd[::-1])

fwd =  [[3 1]
 [1 2]]
 rev =  [[1 2]
 [3 1]]


12. Create a null vector of size 10 but the fifth value which is 1 

In [123]:
nul = np.zeros(10)

nul[5] = 1
nul

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [124]:
mat = np.identity(3) 
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [125]:
ar = np.array([1, 2, 3, 4, 5])
float_val = ar.astype(np.float32)
float_val

array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [126]:
arr1 = np.array([[1., 2., 3.],
                [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
                [7., 2., 12.]])
np.multiply(arr1,arr2)


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [127]:
arr1 = np.array([[1., 2., 3.],
                [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
                [7., 2., 12.]])
print("arr1 > arr2") 
print(np.greater(arr1,arr2)) 
  
print("arr1 >= arr2") 
print(np.greater_equal(arr1,arr2)) 
  
print("arr1 < arr2") 
print(np.less(arr1,arr2)) 
  
print("arr1 <= arr2") 
print(np.less_equal(arr1,arr2)) 

arr1 > arr2
[[ True False  True]
 [False  True False]]
arr1 >= arr2
[[ True False  True]
 [False  True False]]
arr1 < arr2
[[False  True False]
 [ True False  True]]
arr1 <= arr2
[[False  True False]
 [ True False  True]]


17. Extract all odd numbers from arr with values(0-9)

In [128]:
arayodd = np.arange(0,10)
array_odd1 = arayodd[arayodd % 2 == 1]
array_odd1

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [129]:
arayodd[arayodd % 2 == 1] = -1
arayodd

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [130]:
arayodd[5:9]=12
arayodd

array([ 0, -1,  2, -1,  4, 12, 12, 12, 12, -1])

20. Create a 2d array with 1 on the border and 0 inside

In [131]:
ar = np.ones((3, 4))
ar[1:-1, 1:-1] = 0
ar

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [164]:
arr_d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr_d[1:3] = 12
arr_d

array([[ 1,  2,  3],
       [12, 12, 12],
       [12, 12, 12]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [165]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr_3d[0][0] = 64
arr_3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [166]:
aray_2d = np.arange(9).reshape(3,3)
dslice = aray_2d[0]
dslice

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [167]:
aray_2d[1][1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [168]:
aray_2d[0:-1, -1]

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [169]:
from numpy import random
yrandom = random.randint(0,9,size=(10,10))
print (yrandom)
maxval = np.amax(yrandom)
maxval

[[5 5 3 4 4 3 5 4 7 6]
 [2 0 7 8 7 0 3 1 1 5]
 [1 3 6 4 6 6 7 6 0 7]
 [7 4 2 0 8 5 0 6 0 7]
 [7 5 1 5 2 0 5 2 4 2]
 [5 6 4 4 7 0 2 5 0 0]
 [0 6 1 3 2 6 7 3 0 0]
 [0 8 2 0 1 8 7 0 1 2]
 [6 5 6 1 8 0 8 1 3 2]
 [3 3 2 6 0 4 5 3 7 6]]


8

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [170]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [171]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [172]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != 'Will']


array([[-0.60133149,  0.63434661,  0.2791894 ,  1.21539167],
       [-1.20760298, -1.31113786, -0.18868117, -0.57230769],
       [ 0.256019  , -0.94566802,  1.5078795 ,  1.05880895],
       [ 1.09123123,  0.28070246,  0.9423552 ,  1.30969002],
       [-0.6060286 ,  1.01577378,  0.289098  , -0.95911037]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [173]:
data[ (names == 'Bob') | (names == 'Will')]

array([[-0.60133149,  0.63434661,  0.2791894 ,  1.21539167],
       [-1.06387791, -0.24448902, -0.53593204,  0.94318298],
       [ 0.256019  , -0.94566802,  1.5078795 ,  1.05880895],
       [ 0.09924281, -1.78263058,  1.71621804,  0.13650387]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [174]:
rdarr2d = np.random.randint(1,15, size=(5,3))
rdarr2d

array([[12,  3, 10],
       [10,  4,  3],
       [ 1,  1,  2],
       [ 3, 14,  9],
       [ 1,  5,  6]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [175]:
rdarr3d = np.random.randint(1,16, size=(2,2,4))
rdarr3d

array([[[ 6, 11, 12,  4],
        [ 7,  7,  5, 10]],

       [[ 6, 15,  3,  9],
        [ 2,  7,  8, 10]]])

33. Swap axes of the array you created in Question 32

In [176]:
np.swapaxes(rdarr3d,1,2)

array([[[ 6,  7],
        [11,  7],
        [12,  5],
        [ 4, 10]],

       [[ 6,  2],
        [15,  7],
        [ 3,  8],
        [ 9, 10]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [177]:
a10 = np.arange(10)
asqrt = np.sqrt(a10)
aysqrt= np.where(asqrt < 0.5 , 0, asqrt)
aysqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [179]:
random1 = random.randint(10,size=(12))
random2 = random.randint(10,size=(12))
print(random1)
print(random2)
np.maximum(random1,random2)


[1 9 1 7 5 2 0 1 6 3 2 2]
[7 4 4 7 7 0 0 3 1 5 2 9]


array([7, 9, 4, 7, 7, 2, 0, 3, 6, 5, 2, 9])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [180]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [181]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [182]:
Array = np.array([[34,43,73],[82,22,12],[53,94,66]])
Array[:, 1] = 10
Array

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [183]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [184]:
arrayrandom03 = random.randint(100,size=(20))
np.cumsum(arrayrandom03)

array([  10,   39,   76,  166,  169,  268,  349,  382,  430,  526,  610,
        668,  717,  758,  788,  854,  879,  905,  999, 1014], dtype=int32)