# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
import numpy as np

arr = np.arange(0,10).reshape(2,-2)
arr


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [19]:
ar1 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9] ])
ar2 = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.vstack((ar1,ar2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [20]:
ar1 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
ar2 = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

np.hstack((ar1, ar2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [29]:
array = np.asarray([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [36]:
array = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9],[11,12,13,14]]) 
array.ravel()

array([list([0, 1, 2, 3, 4]), list([5, 6, 7, 8, 9]),
       list([11, 12, 13, 14])], dtype=object)

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [51]:
array = np.asarray([0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]).reshape(5, 3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [52]:
ar = np.random.randint(0,5,size=(5, 5))
print("O =", ar)
print("Sq =", np.square(ar))

O = [[2 0 1 2 1]
 [0 2 1 4 4]
 [1 1 4 4 2]
 [2 4 0 4 0]
 [0 0 1 2 2]]
Sq = [[ 4  0  1  4  1]
 [ 0  4  1 16 16]
 [ 1  1 16 16  4]
 [ 4 16  0 16  0]
 [ 0  0  1  4  4]]


## Question:8

### Create 5x6 an array and find the mean?

In [53]:
ar = np.random.randint(0,5,size=(5, 6))
print("Or: ", ar)
print("Mean: ", np.mean(ar))

Or:  [[0 1 1 1 4 0]
 [1 1 2 0 4 3]
 [1 4 3 3 2 4]
 [0 1 0 0 4 4]
 [3 3 2 1 0 1]]
Mean:  1.8


## Question:9

### Find the standard deviation of the previous array in Q8?

In [54]:
print("Standard Deviation: ", np.std(ar))

Standard Deviation:  1.4696938456699067


## Question:10

### Find the median of the previous array in Q8?

In [55]:
print("Medn: ", np.median(ar))

Medn:  1.0


## Question:11

### Find the transpose of the previous array in Q8?

In [56]:
print("Tran: ", np.transpose(ar))

Tran:  [[0 1 1 0 3]
 [1 1 4 1 3]
 [1 2 3 0 2]
 [1 0 3 0 1]
 [4 4 2 4 0]
 [0 3 4 4 1]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [57]:
ard = np.random.randint(0,4,size=(4, 4))
print(ard)
np.trace(ard)


[[3 3 0 1]
 [1 3 0 0]
 [1 2 0 1]
 [0 0 2 3]]


9

## Question:13

### Find the determinant of the previous array in Q12?

In [58]:
np.linalg.det(ard)

-10.000000000000002

## Question:14

### Find the 5th and 95th percentile of an array?

In [60]:
aro = np.random.randint(0,100,size=(4, 4))
print(aro)
print("5th percentile : ", 
       np.percentile(aro, 5))
print("95th percentile : ",
       np.percentile(aro, 95))

[[89 18 20 19]
 [79 39 73 59]
 [29  8  1 72]
 [66 37 70 89]]
5th percentile :  6.25
95th percentile :  89.0


## Question:15

### How to find if a given array has any null values?

In [92]:
array_null=np.array([0,2,3,4,5,6,7])
array_null = array_null.astype('float')
array_null[2]=np.NaN
print(array_null)
array_sum = np.sum(array_null)
array_has_nan = np.isnan(array_sum)
print(array_has_nan)



[ 0.  2. nan  4.  5.  6.  7.]
True
